Project: sprint 1
VitAnd73/middle.messenger.praktikum.yandex pull request #1
Opened 2024-11-06 11:59 UTC by VitAnd73

2024-11-09 20:33 UTC, aromanovnik requested changes
Добрый день, ВБ!

Работа выполнена очень хорошо: проект успешно развернут и работает на Netlify, сразу используется TypeScript, все имена инпутов соответствуют требованиям. Структура проекта продумана: в каждой директории есть индексный файл, экспортирующий только нужные элементы. Код выглядит аккуратно и упорядоченно.

Тем не менее, есть несколько замечаний, которые потребуют доработки. Более подробно о них написано в **комментариях к коду**.

Что нужно исправить:
* В соответствии с семантикой и пунктом 7 чеклиста, заголовки на странице должны быть обёрнуты в соответствующие теги уровней `h1`…`h6`.
* По правилам семантической разметки, весь основной контент страницы следует помещать в тег `main`, расположив его после `header`. 
* Значения атрибутов HTML всегда должны быть заключены в кавычки, даже если внутри используются переменные `Handlebars`. 
* Согласно пункту 7 чеклиста, меню навигации необходимо обернуть в тег `<nav>`.

Что можно улучшить:
* По семантике лучше заменить `<div>` внутри `<label>` на тег `<span>` или `<p>`, поскольку это улучшает доступность и соответствие HTML-спецификациям. 
* Использование `@ts-ignore` считается плохой практикой, поскольку оно подавляет ошибки TypeScript, которые помогают обнаруживать потенциальные проблемы в коде. 
* Рекомендуется удалять все `console.log` и другие отладочные сообщения перед коммитом. 
* Цвета лучше вынести в CSS-переменные, чтобы улучшить читаемость и поддержку кода. 

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-11-09 20:33 UTC, aromanovnik commented on src/main.ts
> +  //@ts-ignore
**Можно лучше**: Использование `@ts-ignore` считается плохой практикой, поскольку оно подавляет ошибки `TypeScript`, которые помогают обнаруживать потенциальные проблемы в коде. В этом случае, вместо типа `string`, лучше настроить правильный тип для `page`, например, указав его как `keyof typeof pages`. Это позволит `TypeScript` проверять корректность значений и поможет предотвратить ошибки, которые могут возникнуть из-за неправильного использования.

2024-11-09 20:33 UTC, aromanovnik commented on src/main.ts
> +  console.log('html', temlpatingFunction(context))
**Можно лучше**: Рекомендуется удалять все `console.log` и другие отладочные сообщения перед коммитом. Это помогает поддерживать чистоту кода и избегать случайного вывода отладочной информации в продакшен-окружении.

2024-11-09 20:33 UTC, aromanovnik commented on src/pages/profile/profile.hbs
> +<div class="container">
**Надо исправить**: По правилам семантической разметки, весь основной контент страницы следует помещать в тег `main`, расположив его после `header`. Это улучшает доступность и структурированность страницы, так как помогает браузерам и скринридерам правильно интерпретировать и навигировать по содержимому.

2024-11-09 20:33 UTC, aromanovnik commented on src/components/input/input.hbs
> +            type={{type}}
**Надо исправить**: Значения атрибутов HTML всегда должны быть заключены в кавычки, даже если внутри используются переменные `Handlebars`. Это соответствует HTML-спецификации и улучшает читаемость, а также предотвращает возможные ошибки парсинга, которые могут возникнуть из-за пробелов или специальных символов.

<img width="1124" alt="Снимок экрана 2024-11-09 в 22 50 12" src="https://github.com/user-attachments/assets/a7bb917d-6e90-4e4c-beb2-178dfa7cc902">

2024-11-09 20:33 UTC, aromanovnik commented on src/components/input/input.hbs
> +        <div class="input__label">{{label}}</div>
**Можно лучше**: По семантике лучше заменить `<div>` внутри `<label>` на тег `<span>` или `<p>`, поскольку это улучшает доступность и соответствие HTML-спецификациям. Вставка `<div>` в `<label>` считается плохой практикой, так как `<div>` — блочный элемент, не предназначенный для вложения в интерактивные элементы. Использование `<span>` или `<p>` более уместно, так как они корректно отображаются внутри `<label>` и передают необходимую информацию без нарушения структуры документа.

2024-11-09 20:33 UTC, aromanovnik commented on src/pages/navigate/navigate.hbs
> +<ul>
**Надо исправить**: Согласно пункту 7 чеклиста, меню навигации необходимо обернуть в тег `<nav>`.

2024-11-09 20:33 UTC, aromanovnik commented on src/pages/profile/profile.css
> +    color: red;
**Можно лучше**: Цвета лучше вынести в CSS-переменные, чтобы улучшить читаемость и поддержку кода. Это позволяет мгновенно понять назначение цвета, избежать дублирования, а также облегчить изменения — достаточно подкорректировать цвет в одном месте, что повышает гибкость и масштабируемость стилей.

2024-11-09 20:33 UTC, aromanovnik commented on src/pages/login/login.hbs
> +        <div class="title">Вход</div>
**Надо исправить**: В соответствии с семантикой и пунктом 7 чеклиста, заголовки на странице должны быть обёрнуты в соответствующие теги уровней `h1`…`h6`. Это помогает соблюсти правильную иерархию заголовков, улучшает доступность для экранных читалок и оптимизирует SEO.

2024-11-10 05:30 UTC, VitAnd73 commented on src/main.ts
> +  //@ts-ignore
Исправлено. Спасибо за комментарий!

2024-11-10 05:30 UTC, VitAnd73 commented on src/main.ts
> +  console.log('html', temlpatingFunction(context))
Удалено.

2024-11-10 05:58 UTC, VitAnd73 commented on src/pages/profile/profile.hbs
> +<div class="container">
Исправлено.

2024-11-10 06:05 UTC, VitAnd73 commented on src/components/input/input.hbs
> +            type={{type}}
Сделано.

2024-11-10 06:07 UTC, VitAnd73 commented on src/components/input/input.hbs
> +        <div class="input__label">{{label}}</div>
Сделано.

2024-11-10 06:08 UTC, VitAnd73 commented on src/pages/navigate/navigate.hbs
> +<ul>
Обернуто в nav.

2024-11-10 06:11 UTC, VitAnd73 commented on src/pages/profile/profile.css
> +    color: red;
Исправлено.

2024-11-10 06:12 UTC, VitAnd73 commented on src/pages/login/login.hbs
> +        <div class="title">Вход</div>
Исправлено.

2024-11-10 06:28 UTC, VitAnd73 commented on src/pages/login/login.hbs
> +        <div class="title">Вход</div>
Сделано

2024-11-10 12:23 UTC, aromanovnik requested changes
Добрый день, ВБ!

Работа проделана огромная, и почти все недочеты исправлены. Однако, к сожалению, необходимо довести до конца оставшиеся задачи. При повторной проверке также выявилось ещё несколько критически важных недочётов, которые требуют доработки. Более подробно о них написано в комментариях к коду.

Что нужно исправить:
* По правилам семантической разметки, весь основной контент **на всех страницах** следует помещать в тег `main`.
* По заданию необходимо реализовать два дополнительных элемента: “**Поле для изменения аватара**” и “**Поля для изменения пароля**”.
* В требованиях указано, что у инпута “**Имя в чате**” атрибут `name` должен быть задан как `display_name`.
* Лишние кавычки в компоненте `input`.

Что можно улучшить:
* Рекомендуется придерживаться макета, указанного в `README.md`.
* Вместо обращения напрямую к нативному тегу в CSS лучше задать для него отдельный CSS-класс (Раньше он был `info__title`, нужно было просто `p` заменить на `h1`). 

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-11-10 12:23 UTC, aromanovnik commented on src/components/info-block/info-block.css
> +h1 {
**Можно лучше**: Вместо обращения напрямую к нативному тегу в CSS лучше задать для него отдельный CSS-класс (Раньше он был `info__title`, нужно было просто `p` заменить на `h1`). Это поможет сохранить работоспособность стилей, если в шаблоне изменятся теги. Код останется гибким и менее подверженным ошибкам, поскольку стили будут связаны с именами классов, а не с конкретными HTML-тегами. [Хорошая статья](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css) не эту тему.

2024-11-10 12:23 UTC, aromanovnik commented on src/pages/profile/profile.hbs
> +            {{> Input label="Имя в чате" name="second_name" placeholder="Иван"}}
**Надо исправить**: В требованиях указано, что у инпута “**Имя в чате**” атрибут `name` должен быть задан как `display_name`.

2024-11-10 12:23 UTC, aromanovnik commented on src/pages/profile/profile.hbs
> +    <section>
**Надо исправить**: По правилам семантической разметки, весь основной контент **на всех страницах** следует помещать в тег `main`.

2024-11-10 12:23 UTC, aromanovnik commented on src/pages/profile/profile.hbs
> +        <img src="{{avatar}}" alt="Avatar" class="avatar">
**Надо исправить**: По заданию необходимо реализовать два дополнительных элемента: “**Поле для изменения аватара**” и “**Поля для изменения пароля”**. Рекомендуется разместить их на отдельных страницах для удобства использования и лучшей структурированности.

<img width="603" alt="Снимок экрана 2024-11-10 в 15 00 13" src="https://github.com/user-attachments/assets/29d21dec-037a-4e04-a4f1-8626d1422aeb">

2024-11-10 12:23 UTC, aromanovnik commented on src/components/input/input.hbs
> +                placeholder="{{placeholder}}""
**Надо исправить**: Лишние кавычки. 

<img width="701" alt="Снимок экрана 2024-11-10 в 15 05 56" src="https://github.com/user-attachments/assets/05de5eac-0aa6-4f13-9091-5354288e3c01">

2024-11-10 12:23 UTC, aromanovnik commented on README.md
> +Макеты находятся по ссылке https://www.figma.com/design/DfjFcaFsHurkWNMo5GgGYh/Chat\_app?node-id=0-1&node-type=canvas
**Можно лучше**: Рекомендуется придерживаться макета, указанного в `README.md`

<img width="1726" alt="Снимок экрана 2024-11-10 в 15 09 59" src="https://github.com/user-attachments/assets/d0ea0602-74cf-40d0-a00e-d953b9ecb255">

2024-11-11 19:59 UTC, VitAnd73 commented on src/components/info-block/info-block.css
> +h1 {
сделано.

2024-11-11 19:59 UTC, VitAnd73 commented on src/pages/profile/profile.hbs
> +            {{> Input label="Имя в чате" name="second_name" placeholder="Иван"}}
исправлено

2024-11-11 20:00 UTC, VitAnd73 commented on src/pages/profile/profile.hbs
> +    <section>
исправлено

2024-11-11 20:00 UTC, VitAnd73 commented on src/pages/profile/profile.hbs
> +        <img src="{{avatar}}" alt="Avatar" class="avatar">
дополнены поля и сделаны дополнительные страницы

2024-11-11 20:01 UTC, VitAnd73 commented on src/components/input/input.hbs
> +                placeholder="{{placeholder}}""
исправлено

2024-11-11 20:01 UTC, VitAnd73 commented on README.md
> +Макеты находятся по ссылке https://www.figma.com/design/DfjFcaFsHurkWNMo5GgGYh/Chat\_app?node-id=0-1&node-type=canvas
исправлено

2024-11-12 11:46 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. 

**Можно лучше**: Использование нескольких тегов `<main>` на одной странице является ошибкой и противоречит спецификации HTML. Элемент `<main>` предназначен для единственного уникального контента, связанного с центральной темой документа или основной функциональностью приложения. Сейчас пропускаю это замечание, но **обязательно исправьте перед сдачей второго спринта**. Рекомендую ознакомиться с хорошей статьей по семантической вёрстке https://htmlacademy.ru/blog/html/semantics .

Желаю успехов в дальнейшей учебе!

2024-11-12 11:46 UTC, aromanovnik commented on src/components/input/input.hbs
> +<main>
**Можно лучше**: Использование нескольких тегов `<main>` на одной странице является ошибкой и противоречит спецификации HTML. Элемент `<main>` предназначен для единственного уникального контента, связанного с центральной темой документа или основной функциональностью приложения. Сейчас пропускаю это замечание, но **обязательно исправьте перед сдачей второго спринта**. Рекомендую ознакомиться с хорошей статьей по семантической вёрстке https://htmlacademy.ru/blog/html/semantics .

2024-11-21 18:12 UTC, VitAnd73 commented on src/components/input/input.hbs
> +<main>
Учтено. Спасибо!

2024-11-21 18:12 UTC, merged